// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hQFfKpZEgq6qg2o6gPpxGxaxfgsWyR0',
    appId: '1:1016768731650:android:af761f9e56f67c0e93e51b',
    messagingSenderId: '1016768731650',
    projectId: 'iz-stock-app',
    storageBucket: 'iz-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcUKX6poPGeeA5CTfFdaEBgHUWwpRFBBA',
    appId: '1:1016768731650:ios:21f1f99c7cab01f993e51b',
    messagingSenderId: '1016768731650',
    projectId: 'iz-stock-app',
    storageBucket: 'iz-stock-app.firebasestorage.app',
    iosBundleId: 'com.example.izstock',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdzwiOF7Esvuz644lUAdMRO_NJDJkKk8',
    appId: '1:1016768731650:web:4a5373042a75442493e51b',
    messagingSenderId: '1016768731650',
    projectId: 'iz-stock-app',
    authDomain: 'iz-stock-app.firebaseapp.com',
    storageBucket: 'iz-stock-app.firebasestorage.app',
  );

}